"""Per-file content descriptions — a JSON sidecar in the LanceDB directory.

Maps `table_name -> {file, description, language, chunk_overlap}`. Written at
index time, read by the Planner (via `list_collections_described`) so it can
pick which collection to search from a short summary, not just the table name;
`language` (ISO 639-1) drives FTS stemmer choice and cross-lingual query
rewriting. Legacy sidecars without `language` → `"ru"`.

The sidecar also carries `_meta.embedding_model` and `_meta.embedding_dim` —
written at index time so a provider/model change that invalidates existing
vectors is caught at search time with a clear "full reindex required" error
instead of silently returning garbage distances.

Storage only — the description text is generated by the caller's LLM and passed
in (keeps this module, and the indexer, free of any agent/LLM dependency).
"""

import json
from pathlib import Path

from src.vectordb.config import vdb_settings

_FILENAME = "_descriptions.json"
_META_KEY = "_meta"


def _path(db_path: str | None) -> Path:
    return Path(db_path or vdb_settings.lance_db_path) / _FILENAME


def load_descriptions(db_path: str | None = None) -> dict[str, dict]:
    """Read the sidecar; empty dict if absent or unreadable."""
    p = _path(db_path)
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def save_descriptions(
    db_path: str | None,
    descriptions: dict[str, dict],
    *,
    embedding_model: str | None = None,
    embedding_dim: int | None = None,
) -> None:
    """Overwrite the sidecar with the current run's descriptions.

    *embedding_model* and *embedding_dim* are stamped into a `_meta` key so a
    later provider/model change that invalidates existing vectors is caught at
    search time rather than silently returning broken distances.
    """
    data = dict(descriptions)
    if _META_KEY in data:
        meta = dict(data[_META_KEY])
    else:
        meta = {}
    if embedding_model is not None:
        meta["embedding_model"] = embedding_model
    if embedding_dim is not None:
        meta["embedding_dim"] = embedding_dim
    if meta:
        data[_META_KEY] = meta
    p = _path(db_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8"
    )


def validate_embedding_model(
    db_path: str | None = None,
    *,
    expected_model: str | None = None,
    expected_dim: int | None = None,
) -> None:
    """Raise ``ValueError`` if the sidecar's embedding model/dim don't match.

    Legacy sidecars (no ``_meta``) pass silently — they were indexed before this
    check existed and may predate the current model; the user accepts the risk.

    Called at search time (via ``vector_search`` / ``list_collections_described``)
    so a mismatch is caught on the very first query after a provider change,
    before any garbage distances reach the judge.
    """
    data = load_descriptions(db_path)
    meta = data.get(_META_KEY)
    if meta is None:
        return  # legacy — no metadata to check
    if expected_model is not None:
        stored = meta.get("embedding_model")
        if stored and stored != expected_model:
            raise ValueError(
                f"Embedding model mismatch: the index was built with "
                f"«{stored}», but the current provider uses "
                f"«{expected_model}». A full reindex is required — the "
                f"existing vectors are incompatible with the new model."
            )
    if expected_dim is not None:
        stored_dim = meta.get("embedding_dim")
        if stored_dim is not None and stored_dim != expected_dim:
            raise ValueError(
                f"Embedding dimension mismatch: the index was built with "
                f"{stored_dim}d vectors, but the current model produces "
                f"{expected_dim}d vectors. A full reindex is required."
            )


def language_for_collection(
    collection: str, db_path: str | None = None, descriptions: dict | None = None
) -> str:
    """ISO 639-1 language code for a collection, or "ru" if unknown (legacy).

    Single access point — the rewriter and the indexer both go through it so
    the fallback is consistent.
    """
    if descriptions is None:
        descriptions = load_descriptions(db_path)
    info = descriptions.get(collection, {})
    lang = (info.get("language") or "").strip().lower()
    return lang if lang else "ru"
