"""Per-file content descriptions — a JSON sidecar in the LanceDB directory.

Maps `table_name -> {file, description}`. Written at index time, read by the
Planner (via `list_collections_described`) so it can pick which collection to
search from a short summary, not just the table name.

Storage only — the description text is generated by the caller's LLM and passed
in (keeps this module, and the indexer, free of any agent/LLM dependency).
"""

import json
from pathlib import Path

from src.vectordb.config import vdb_settings

_FILENAME = "_descriptions.json"


def _path(db_path: str | None) -> Path:
    return Path(db_path or vdb_settings.lance_db_path) / _FILENAME


def load_descriptions(db_path: str | None = None) -> dict[str, dict]:
    """Read the sidecar; empty dict if absent or unreadable."""
    p = _path(db_path)
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def save_descriptions(db_path: str | None, descriptions: dict[str, dict]) -> None:
    """Overwrite the sidecar with the current run's descriptions."""
    p = _path(db_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        json.dumps(descriptions, ensure_ascii=False, indent=2), encoding="utf-8"
    )
